
_banner.htm,备用顶部banner
_header.htm,公共头部
_footer.htm,公共底部
_link.htm,公共样式
_meta.htm,公共meta信息
_script.htm,公共脚本
_sj_copyright.htm,公共版权声明
_news_project.htm,新闻随机项目
_home_project.htm,推荐项目文章
_question.htm,问答
_theway.htm,theway


index.htm,主页模板
ajaxfeedback.htm,Ajax评论模板
article_article.htm,文章内容页模板
article_article1.htm,随机文章内容页模板1
article_article2.htm,随机文章内容页模板2
article_article_frame.htm,文章内容页模板框架版
article_default.htm,自定义文档内容模板
article_default_sg.htm,自定义单表文档内容模板
article_image.htm,图片集内容页模板
article_image_cl.htm,图片集内容页模板(新图集样式)
article_image_frame.htm,图片集内容页模板框架版
article_shop.htm,商品模型内容页模板
article_soft.htm,软件内容页模板
article_soft_frame.htm,软件内容页模板框架版
article_infos.htm,分类信息内容模板
article_spec.htm,专题内容页模板
index_article.htm,文章频道封面
index_default.htm,默认频道封面
index_default_sg.htm,默认单表模型频道封面
index_image.htm,默认图片模型封面
index_shop.htm,默认网店模型封面
index_soft.htm,默认软件模型封面
infosw9_index.htm,默认图文资讯封面
infosw9_list.htm,默认图文资讯列表页
index_infos.htm,分类信息封面模板
list_article.htm,默认文章列表模板
list_default.htm,默认自定义模型列表模板

list_case.htm,案例列表模板
list_chain.htm,连锁店列表模板
list_chanping.htm,产品列表模板
list_chanping1.htm,产品1列表模板
list_chanping2.htm,产品2列表模板
list_equip.htm,设备列表模板
list_news.htm,新闻列表模板
list_project.htm,项目列表模板

chain_item.htm,连锁店电话和地址页