
_banner.htm,备用顶部banner
_header.htm,公共头部
_footer.htm,公共底部
_link.htm,公共样式
_meta.htm,公共meta信息
_script.htm,公共脚本
_sj_copyright.htm,公共版权声明
_news_project.htm,新闻随机项目
_home_project.htm,推荐项目文章
_question.htm,问答
_theway.htm,theway


index.htm,主页模板
article_article.htm,文章内容页模板
article_default.htm,自定义文档内容模板
article_chain.htm,连锁店内容页模板
article_news.htm,新闻内容页模板
article_case.htm,案例内容页模板
article_chanping.htm,产品内容页模板框架版
article_equip.htm,设备内容模板
article_project.htm,项目内容页模板
index_brand.htm,品牌频道封面
index_default.htm,默认频道封面
index_chanping.htm,产品模型频道封面
list_article.htm,默认文章列表模板
list_default.htm,默认自定义模型列表模板
list_case.htm,案例列表模板
list_chain.htm,连锁店列表模板
list_chanping.htm,产品列表模板
list_chanping1.htm,产品1列表模板
list_chanping2.htm,产品2列表模板
list_equip.htm,设备列表模板
list_news.htm,新闻列表模板
list_project.htm,项目列表模板

