
<field:pic_before itemname="术前照片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_before>

<field:pic_after1 itemname="术后照片（首页）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_after1>

<field:pic_after2 itemname="术后照片（pc大图）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_after2>
