
<field:pic1 itemname="产品图（pc轮播）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic1>

<field:pic2 itemname="产品图（sj列表大图）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic2>

<field:pic3 itemname="产品图（sj列表小图）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic3>
