
<field:pic1 itemname="设备图（pc首页图）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic1>

<field:pic2 itemname="设备图1（pc列表图轮播）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic2>


<field:pic3 itemname="设备图2（pc列表图轮播）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic3>

<field:pic4 itemname="设备图（sj列表）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic4>
