
<field:pic_before itemname="术前照片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_before>

<field:pic_after1 itemname="术后照片（首页）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_after1>

<field:pic_after2 itemname="术后照片（pc大图）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_after2>

<field:pic_after3 itemname="术后照片（手机大图）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pic_after3>



<field:doctor itemname="服务技师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:doctor>

<field:project1 itemname="项目1(pc端单个展示)" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:project1>
