
<field:tel itemname="热线" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:tel>

<field:address itemname="地址 " autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:address>

<field:s_pic1 itemname="环境小图1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_pic1>

<field:s_pic2 itemname="环境小图2" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_pic2>

<field:s_pic3 itemname="环境小图3" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_pic3>

<field:s_pic4 itemname="环境小图4" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_pic4>

<field:s_pic5 itemname="环境小图5" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_pic5>


<field:s_pic6 itemname="环境小图6" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:s_pic6>


<field:b_pic1 itemname="环境大图1" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:b_pic1>
